-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.30 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table lib_client.areas
CREATE TABLE IF NOT EXISTS `areas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `district_id` bigint unsigned DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `en_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `areas_district_id_foreign` (`district_id`),
  CONSTRAINT `areas_district_id_foreign` FOREIGN KEY (`district_id`) REFERENCES `districts` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=546 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table lib_client.areas: ~545 rows (approximately)
INSERT INTO `areas` (`id`, `district_id`, `name`, `en_name`, `created_at`, `updated_at`, `deleted_at`) VALUES
	(1, 1, 'দেবিদ্বার', 'Debidwar', NULL, NULL, NULL),
	(2, 1, 'বরুড়া', 'Barura', NULL, NULL, NULL),
	(3, 1, 'ব্রাহ্মণপাড়া', 'Brahmanpara', NULL, NULL, NULL),
	(4, 1, 'চান্দিনা', 'Chandina', NULL, NULL, NULL),
	(5, 1, 'চৌদ্দগ্রাম', 'Chauddagram', NULL, NULL, NULL),
	(6, 1, 'দাউদকান্দি', 'Daudkandi', NULL, NULL, NULL),
	(7, 1, 'হোমনা', 'Homna', NULL, NULL, NULL),
	(8, 1, 'লাকসাম', 'Laksam', NULL, NULL, NULL),
	(9, 1, 'মুরাদনগর', 'Muradnagar', NULL, NULL, NULL),
	(10, 1, 'নাঙ্গলকোট', 'Nangalkot', NULL, NULL, NULL),
	(11, 1, 'কুমিল্লা সদর', 'Comilla Sadar', NULL, NULL, NULL),
	(12, 1, 'মেঘনা', 'Meghna', NULL, NULL, NULL),
	(13, 1, 'মনোহরগঞ্জ', 'Monohargonj', NULL, NULL, NULL),
	(14, 1, 'সদর দক্ষিণ', 'Sadarsouth', NULL, NULL, NULL),
	(15, 1, 'তিতাস', 'Titas', NULL, NULL, NULL),
	(16, 1, 'বুড়িচং', 'Burichang', NULL, NULL, NULL),
	(17, 1, 'লালমাই', 'Lalmai', NULL, NULL, NULL),
	(18, 2, 'ছাগলনাইয়া', 'Chhagalnaiya', NULL, NULL, NULL),
	(19, 2, 'ফেনী সদর', 'Feni Sadar', NULL, NULL, NULL),
	(20, 2, 'সোনাগাজী', 'Sonagazi', NULL, NULL, NULL),
	(21, 2, 'ফুলগাজী', 'Fulgazi', NULL, NULL, NULL),
	(22, 2, 'পরশুরাম', 'Parshuram', NULL, NULL, NULL),
	(23, 2, 'দাগনভূঞা', 'Daganbhuiyan', NULL, NULL, NULL),
	(24, 3, 'ব্রাহ্মণবাড়িয়া সদর', 'Brahmanbaria Sadar', NULL, NULL, NULL),
	(25, 3, 'কসবা', 'Kasba', NULL, NULL, NULL),
	(26, 3, 'নাসিরনগর', 'Nasirnagar', NULL, NULL, NULL),
	(27, 3, 'সরাইল', 'Sarail', NULL, NULL, NULL),
	(28, 3, 'আশুগঞ্জ', 'Ashuganj', NULL, NULL, NULL),
	(29, 3, 'আখাউড়া', 'Akhaura', NULL, NULL, NULL),
	(30, 3, 'নবীনগর', 'Nabinagar', NULL, NULL, NULL),
	(31, 3, 'বাঞ্ছারামপুর', 'Bancharampur', NULL, NULL, NULL),
	(32, 3, 'বিজয়নগর', 'Bijoynagar', NULL, NULL, NULL),
	(33, 4, 'রাঙ্গামাটি সদর', 'Rangamati Sadar', NULL, NULL, NULL),
	(34, 4, 'কাপ্তাই', 'Kaptai', NULL, NULL, NULL),
	(35, 4, 'কাউখালী', 'Kawkhali', NULL, NULL, NULL),
	(36, 4, 'বাঘাইছড়ি', 'Baghaichari', NULL, NULL, NULL),
	(37, 4, 'বরকল', 'Barkal', NULL, NULL, NULL),
	(38, 4, 'লংগদু', 'Langadu', NULL, NULL, NULL),
	(39, 4, 'রাজস্থলী', 'Rajasthali', NULL, NULL, NULL),
	(40, 4, 'বিলাইছড়ি', 'Belaichari', NULL, NULL, NULL),
	(41, 4, 'জুরাছড়ি', 'Juraichari', NULL, NULL, NULL),
	(42, 4, 'নানিয়ারচর', 'Naniarchar', NULL, NULL, NULL),
	(43, 5, 'নোয়াখালী সদর', 'Noakhali Sadar', NULL, NULL, NULL),
	(44, 5, 'কোম্পানীগঞ্জ', 'Companiganj', NULL, NULL, NULL),
	(45, 5, 'বেগমগঞ্জ', 'Begumganj', NULL, NULL, NULL),
	(46, 5, 'হাতিয়া', 'Hatia', NULL, NULL, NULL),
	(47, 5, 'সুবর্ণচর', 'Subarnachar', NULL, NULL, NULL),
	(48, 5, 'কবিরহাট', 'Kabirhat', NULL, NULL, NULL),
	(49, 5, 'সেনবাগ', 'Senbug', NULL, NULL, NULL),
	(50, 5, 'চাটখিল', 'Chatkhil', NULL, NULL, NULL),
	(51, 5, 'সোনাইমুড়ী', 'Sonaimori', NULL, NULL, NULL),
	(52, 6, 'হাইমচর', 'Haimchar', NULL, NULL, NULL),
	(53, 6, 'কচুয়া', 'Kachua', NULL, NULL, NULL),
	(54, 6, 'শাহরাস্তি	', 'Shahrasti', NULL, NULL, NULL),
	(55, 6, 'চাঁদপুর সদর', 'Chandpur Sadar', NULL, NULL, NULL),
	(56, 6, 'মতলব দক্ষিণ', 'Matlab South', NULL, NULL, NULL),
	(57, 6, 'হাজীগঞ্জ', 'Hajiganj', NULL, NULL, NULL),
	(58, 6, 'মতলব উত্তর', 'Matlab North', NULL, NULL, NULL),
	(59, 6, 'ফরিদগঞ্জ', 'Faridgonj', NULL, NULL, NULL),
	(60, 7, 'লক্ষ্মীপুর সদর', 'Lakshmipur Sadar', NULL, NULL, NULL),
	(61, 7, 'কমলনগর', 'Kamalnagar', NULL, NULL, NULL),
	(62, 7, 'রায়পুর', 'Raipur', NULL, NULL, NULL),
	(63, 7, 'রামগতি', 'Ramgati', NULL, NULL, NULL),
	(64, 7, 'রামগঞ্জ', 'Ramganj', NULL, NULL, NULL),
	(65, 8, 'রাঙ্গুনিয়া', 'Rangunia', NULL, NULL, NULL),
	(66, 8, 'সীতাকুন্ড', 'Sitakunda', NULL, NULL, NULL),
	(67, 8, 'মীরসরাই', 'Mirsharai', NULL, NULL, NULL),
	(68, 8, 'পটিয়া', 'Patiya', NULL, NULL, NULL),
	(69, 8, 'সন্দ্বীপ', 'Sandwip', NULL, NULL, NULL),
	(70, 8, 'বাঁশখালী', 'Banshkhali', NULL, NULL, NULL),
	(71, 8, 'বোয়ালখালী', 'Boalkhali', NULL, NULL, NULL),
	(72, 8, 'আনোয়ারা', 'Anwara', NULL, NULL, NULL),
	(73, 8, 'চন্দনাইশ', 'Chandanaish', NULL, NULL, NULL),
	(74, 8, 'সাতকানিয়া', 'Satkania', NULL, NULL, NULL),
	(75, 8, 'লোহাগাড়া', 'Lohagara', NULL, NULL, NULL),
	(76, 8, 'হাটহাজারী', 'Hathazari', NULL, NULL, NULL),
	(77, 8, 'ফটিকছড়ি', 'Fatikchhari', NULL, NULL, NULL),
	(78, 8, 'রাউজান', 'Raozan', NULL, NULL, NULL),
	(79, 8, 'কর্ণফুলী', 'Karnafuli', NULL, NULL, NULL),
	(80, 9, 'কক্সবাজার সদর', 'Coxsbazar Sadar', NULL, NULL, NULL),
	(81, 9, 'চকরিয়া', 'Chakaria', NULL, NULL, NULL),
	(82, 9, 'কুতুবদিয়া', 'Kutubdia', NULL, NULL, NULL),
	(83, 9, 'উখিয়া', 'Ukhiya', NULL, NULL, NULL),
	(84, 9, 'মহেশখালী', 'Moheshkhali', NULL, NULL, NULL),
	(85, 9, 'পেকুয়া', 'Pekua', NULL, NULL, NULL),
	(86, 9, 'রামু', 'Ramu', NULL, NULL, NULL),
	(87, 9, 'টেকনাফ', 'Teknaf', NULL, NULL, NULL),
	(88, 10, 'খাগড়াছড়ি সদর', 'Khagrachhari Sadar', NULL, NULL, NULL),
	(89, 10, 'দিঘীনালা', 'Dighinala', NULL, NULL, NULL),
	(90, 10, 'পানছড়ি', 'Panchari', NULL, NULL, NULL),
	(91, 10, 'লক্ষীছড়ি', 'Laxmichhari', NULL, NULL, NULL),
	(92, 10, 'মহালছড়ি', 'Mohalchari', NULL, NULL, NULL),
	(93, 10, 'মানিকছড়ি', 'Manikchari', NULL, NULL, NULL),
	(94, 10, 'রামগড়', 'Ramgarh', NULL, NULL, NULL),
	(95, 10, 'মাটিরাঙ্গা', 'Matiranga', NULL, NULL, NULL),
	(96, 10, 'গুইমারা', 'Guimara', NULL, NULL, NULL),
	(97, 11, 'বান্দরবান সদর', 'Bandarban Sadar', NULL, NULL, NULL),
	(98, 11, 'আলীকদম', 'Alikadam', NULL, NULL, NULL),
	(99, 11, 'নাইক্ষ্যংছড়ি', 'Naikhongchhari', NULL, NULL, NULL),
	(100, 11, 'রোয়াংছড়ি', 'Rowangchhari', NULL, NULL, NULL),
	(101, 11, 'লামা', 'Lama', NULL, NULL, NULL),
	(102, 11, 'রুমা', 'Ruma', NULL, NULL, NULL),
	(103, 11, 'থানচি', 'Thanchi', NULL, NULL, NULL),
	(104, 12, 'বেলকুচি', 'Belkuchi', NULL, NULL, NULL),
	(105, 12, 'চৌহালি', 'Chauhali', NULL, NULL, NULL),
	(106, 12, 'কামারখন্দ', 'Kamarkhand', NULL, NULL, NULL),
	(107, 12, 'কাজীপুর', 'Kazipur', NULL, NULL, NULL),
	(108, 12, 'রায়গঞ্জ', 'Raigonj', NULL, NULL, NULL),
	(109, 12, 'শাহজাদপুর', 'Shahjadpur', NULL, NULL, NULL),
	(110, 12, 'সিরাজগঞ্জ সদর', 'Sirajganj Sadar', NULL, NULL, NULL),
	(111, 12, 'তাড়াশ', 'Tarash', NULL, NULL, NULL),
	(112, 12, 'উল্লাপাড়া', 'Ullapara', NULL, NULL, NULL),
	(113, 13, 'সুজানগর', 'Sujanagar', NULL, NULL, NULL),
	(114, 13, 'ঈশ্বরদী', 'Ishurdi', NULL, NULL, NULL),
	(115, 13, 'ভাঙ্গুড়া', 'Bhangura', NULL, NULL, NULL),
	(116, 13, 'পাবনা সদর', 'Pabna Sadar', NULL, NULL, NULL),
	(117, 13, 'বেড়া', 'Bera', NULL, NULL, NULL),
	(118, 13, 'আটঘরিয়া', 'Atghoria', NULL, NULL, NULL),
	(119, 13, 'চাটমোহর', 'Chatmohar', NULL, NULL, NULL),
	(120, 13, 'সাঁথিয়া', 'Santhia', NULL, NULL, NULL),
	(121, 13, 'ফরিদপুর', 'Faridpur', NULL, NULL, NULL),
	(122, 14, 'কাহালু', 'Kahaloo', NULL, NULL, NULL),
	(123, 14, 'বগুড়া সদর', 'Bogra Sadar', NULL, NULL, NULL),
	(124, 14, 'সারিয়াকান্দি', 'Shariakandi', NULL, NULL, NULL),
	(125, 14, 'শাজাহানপুর', 'Shajahanpur', NULL, NULL, NULL),
	(126, 14, 'দুপচাচিঁয়া', 'Dupchanchia', NULL, NULL, NULL),
	(127, 14, 'আদমদিঘি', 'Adamdighi', NULL, NULL, NULL),
	(128, 14, 'নন্দিগ্রাম', 'Nondigram', NULL, NULL, NULL),
	(129, 14, 'সোনাতলা', 'Sonatala', NULL, NULL, NULL),
	(130, 14, 'ধুনট', 'Dhunot', NULL, NULL, NULL),
	(131, 14, 'গাবতলী', 'Gabtali', NULL, NULL, NULL),
	(132, 14, 'শেরপুর', 'Sherpur', NULL, NULL, NULL),
	(133, 14, 'শিবগঞ্জ', 'Shibganj', NULL, NULL, NULL),
	(134, 15, 'পবা', 'Paba', NULL, NULL, NULL),
	(135, 15, 'দুর্গাপুর', 'Durgapur', NULL, NULL, NULL),
	(136, 15, 'মোহনপুর', 'Mohonpur', NULL, NULL, NULL),
	(137, 15, 'চারঘাট', 'Charghat', NULL, NULL, NULL),
	(138, 15, 'পুঠিয়া', 'Puthia', NULL, NULL, NULL),
	(139, 15, 'বাঘা', 'Bagha', NULL, NULL, NULL),
	(140, 15, 'গোদাগাড়ী', 'Godagari', NULL, NULL, NULL),
	(141, 15, 'তানোর', 'Tanore', NULL, NULL, NULL),
	(142, 15, 'বাগমারা', 'Bagmara', NULL, NULL, NULL),
	(143, 16, 'নাটোর সদর', 'Natore Sadar', NULL, NULL, NULL),
	(144, 16, 'সিংড়া', 'Singra', NULL, NULL, NULL),
	(145, 16, 'বড়াইগ্রাম', 'Baraigram', NULL, NULL, NULL),
	(146, 16, 'বাগাতিপাড়া', 'Bagatipara', NULL, NULL, NULL),
	(147, 16, 'লালপুর', 'Lalpur', NULL, NULL, NULL),
	(148, 16, 'গুরুদাসপুর', 'Gurudaspur', NULL, NULL, NULL),
	(149, 16, 'নলডাঙ্গা', 'Naldanga', NULL, NULL, NULL),
	(150, 17, 'আক্কেলপুর', 'Akkelpur', NULL, NULL, NULL),
	(151, 17, 'কালাই', 'Kalai', NULL, NULL, NULL),
	(152, 17, 'ক্ষেতলাল', 'Khetlal', NULL, NULL, NULL),
	(153, 17, 'পাঁচবিবি', 'Panchbibi', NULL, NULL, NULL),
	(154, 17, 'জয়পুরহাট সদর', 'Joypurhat Sadar', NULL, NULL, NULL),
	(155, 18, 'চাঁপাইনবাবগঞ্জ সদর', 'Chapainawabganj Sadar', NULL, NULL, NULL),
	(156, 18, 'গোমস্তাপুর', 'Gomostapur', NULL, NULL, NULL),
	(157, 18, 'নাচোল', 'Nachol', NULL, NULL, NULL),
	(158, 18, 'ভোলাহাট', 'Bholahat', NULL, NULL, NULL),
	(159, 18, 'শিবগঞ্জ', 'Shibganj', NULL, NULL, NULL),
	(160, 19, 'মহাদেবপুর', 'Mohadevpur', NULL, NULL, NULL),
	(161, 19, 'বদলগাছী', 'Badalgachi', NULL, NULL, NULL),
	(162, 19, 'পত্নিতলা', 'Patnitala', NULL, NULL, NULL),
	(163, 19, 'ধামইরহাট', 'Dhamoirhat', NULL, NULL, NULL),
	(164, 19, 'নিয়ামতপুর', 'Niamatpur', NULL, NULL, NULL),
	(165, 19, 'মান্দা', 'Manda', NULL, NULL, NULL),
	(166, 19, 'আত্রাই', 'Atrai', NULL, NULL, NULL),
	(167, 19, 'রাণীনগর', 'Raninagar', NULL, NULL, NULL),
	(168, 19, 'নওগাঁ সদর', 'Naogaon Sadar', NULL, NULL, NULL),
	(169, 19, 'পোরশা', 'Porsha', NULL, NULL, NULL),
	(170, 19, 'সাপাহার', 'Sapahar', NULL, NULL, NULL),
	(171, 20, 'মণিরামপুর', 'Manirampur', NULL, NULL, NULL),
	(172, 20, 'অভয়নগর', 'Abhaynagar', NULL, NULL, NULL),
	(173, 20, 'বাঘারপাড়া', 'Bagherpara', NULL, NULL, NULL),
	(174, 20, 'চৌগাছা', 'Chougachha', NULL, NULL, NULL),
	(175, 20, 'ঝিকরগাছা', 'Jhikargacha', NULL, NULL, NULL),
	(176, 20, 'কেশবপুর', 'Keshabpur', NULL, NULL, NULL),
	(177, 20, 'যশোর সদর', 'Jessore Sadar', NULL, NULL, NULL),
	(178, 20, 'শার্শা', 'Sharsha', NULL, NULL, NULL),
	(179, 21, 'আশাশুনি', 'Assasuni', NULL, NULL, NULL),
	(180, 21, 'দেবহাটা', 'Debhata', NULL, NULL, NULL),
	(181, 21, 'কলারোয়া', 'Kalaroa', NULL, NULL, NULL),
	(182, 21, 'সাতক্ষীরা সদর', 'Satkhira Sadar', NULL, NULL, NULL),
	(183, 21, 'শ্যামনগর', 'Shyamnagar', NULL, NULL, NULL),
	(184, 21, 'তালা', 'Tala', NULL, NULL, NULL),
	(185, 21, 'কালিগঞ্জ', 'Kaliganj', NULL, NULL, NULL),
	(186, 22, 'মুজিবনগর', 'Mujibnagar', NULL, NULL, NULL),
	(187, 22, 'মেহেরপুর সদর', 'Meherpur Sadar', NULL, NULL, NULL),
	(188, 22, 'গাংনী', 'Gangni', NULL, NULL, NULL),
	(189, 23, 'নড়াইল সদর', 'Narail Sadar', NULL, NULL, NULL),
	(190, 23, 'লোহাগড়া', 'Lohagara', NULL, NULL, NULL),
	(191, 23, 'কালিয়া', 'Kalia', NULL, NULL, NULL),
	(192, 24, 'চুয়াডাঙ্গা সদর', 'Chuadanga Sadar', NULL, NULL, NULL),
	(193, 24, 'আলমডাঙ্গা', 'Alamdanga', NULL, NULL, NULL),
	(194, 24, 'দামুড়হুদা', 'Damurhuda', NULL, NULL, NULL),
	(195, 24, 'জীবননগর', 'Jibannagar', NULL, NULL, NULL),
	(196, 25, 'কুষ্টিয়া সদর', 'Kushtia Sadar', NULL, NULL, NULL),
	(197, 25, 'কুমারখালী', 'Kumarkhali', NULL, NULL, NULL),
	(198, 25, 'খোকসা', 'Khoksa', NULL, NULL, NULL),
	(199, 25, 'মিরপুর', 'Mirpur', NULL, NULL, NULL),
	(200, 25, 'দৌলতপুর', 'Daulatpur', NULL, NULL, NULL),
	(201, 25, 'ভেড়ামারা', 'Bheramara', NULL, NULL, NULL),
	(202, 26, 'শালিখা', 'Shalikha', NULL, NULL, NULL),
	(203, 26, 'শ্রীপুর', 'Sreepur', NULL, NULL, NULL),
	(204, 26, 'মাগুরা সদর', 'Magura Sadar', NULL, NULL, NULL),
	(205, 26, 'মহম্মদপুর', 'Mohammadpur', NULL, NULL, NULL),
	(206, 27, 'পাইকগাছা', 'Paikgasa', NULL, NULL, NULL),
	(207, 27, 'ফুলতলা', 'Fultola', NULL, NULL, NULL),
	(208, 27, 'দিঘলিয়া', 'Digholia', NULL, NULL, NULL),
	(209, 27, 'রূপসা', 'Rupsha', NULL, NULL, NULL),
	(210, 27, 'তেরখাদা', 'Terokhada', NULL, NULL, NULL),
	(211, 27, 'ডুমুরিয়া', 'Dumuria', NULL, NULL, NULL),
	(212, 27, 'বটিয়াঘাটা', 'Botiaghata', NULL, NULL, NULL),
	(213, 27, 'দাকোপ', 'Dakop', NULL, NULL, NULL),
	(214, 27, 'কয়রা', 'Koyra', NULL, NULL, NULL),
	(215, 28, 'ফকিরহাট', 'Fakirhat', NULL, NULL, NULL),
	(216, 28, 'বাগেরহাট সদর', 'Bagerhat Sadar', NULL, NULL, NULL),
	(217, 28, 'মোল্লাহাট', 'Mollahat', NULL, NULL, NULL),
	(218, 28, 'শরণখোলা', 'Sarankhola', NULL, NULL, NULL),
	(219, 28, 'রামপাল', 'Rampal', NULL, NULL, NULL),
	(220, 28, 'মোড়েলগঞ্জ', 'Morrelganj', NULL, NULL, NULL),
	(221, 28, 'কচুয়া', 'Kachua', NULL, NULL, NULL),
	(222, 28, 'মোংলা', 'Mongla', NULL, NULL, NULL),
	(223, 28, 'চিতলমারী', 'Chitalmari', NULL, NULL, NULL),
	(224, 29, 'ঝিনাইদহ সদর', 'Jhenaidah Sadar', NULL, NULL, NULL),
	(225, 29, 'শৈলকুপা', 'Shailkupa', NULL, NULL, NULL),
	(226, 29, 'হরিণাকুন্ডু', 'Harinakundu', NULL, NULL, NULL),
	(227, 29, 'কালীগঞ্জ', 'Kaliganj', NULL, NULL, NULL),
	(228, 29, 'কোটচাঁদপুর', 'Kotchandpur', NULL, NULL, NULL),
	(229, 29, 'মহেশপুর', 'Moheshpur', NULL, NULL, NULL),
	(230, 30, 'ঝালকাঠি সদর', 'Jhalakathi Sadar', NULL, NULL, NULL),
	(231, 30, 'কাঠালিয়া', 'Kathalia', NULL, NULL, NULL),
	(232, 30, 'নলছিটি', 'Nalchity', NULL, NULL, NULL),
	(233, 30, 'রাজাপুর', 'Rajapur', NULL, NULL, NULL),
	(234, 31, 'বাউফল', 'Bauphal', NULL, NULL, NULL),
	(235, 31, 'পটুয়াখালী সদর', 'Patuakhali Sadar', NULL, NULL, NULL),
	(236, 31, 'দুমকি', 'Dumki', NULL, NULL, NULL),
	(237, 31, 'দশমিনা', 'Dashmina', NULL, NULL, NULL),
	(238, 31, 'কলাপাড়া', 'Kalapara', NULL, NULL, NULL),
	(239, 31, 'মির্জাগঞ্জ', 'Mirzaganj', NULL, NULL, NULL),
	(240, 31, 'গলাচিপা', 'Galachipa', NULL, NULL, NULL),
	(241, 31, 'রাঙ্গাবালী', 'Rangabali', NULL, NULL, NULL),
	(242, 32, 'পিরোজপুর সদর', 'Pirojpur Sadar', NULL, NULL, NULL),
	(243, 32, 'নাজিরপুর', 'Nazirpur', NULL, NULL, NULL),
	(244, 32, 'কাউখালী', 'Kawkhali', NULL, NULL, NULL),
	(245, 32, 'জিয়ানগর', 'Zianagar', NULL, NULL, NULL),
	(246, 32, 'ভান্ডারিয়া', 'Bhandaria', NULL, NULL, NULL),
	(247, 32, 'মঠবাড়ীয়া', 'Mathbaria', NULL, NULL, NULL),
	(248, 32, 'নেছারাবাদ', 'Nesarabad', NULL, NULL, NULL),
	(249, 33, 'বরিশাল সদর', 'Barisal Sadar', NULL, NULL, NULL),
	(250, 33, 'বাকেরগঞ্জ', 'Bakerganj', NULL, NULL, NULL),
	(251, 33, 'বাবুগঞ্জ', 'Babuganj', NULL, NULL, NULL),
	(252, 33, 'উজিরপুর', 'Wazirpur', NULL, NULL, NULL),
	(253, 33, 'বানারীপাড়া', 'Banaripara', NULL, NULL, NULL),
	(254, 33, 'গৌরনদী', 'Gournadi', NULL, NULL, NULL),
	(255, 33, 'আগৈলঝাড়া', 'Agailjhara', NULL, NULL, NULL),
	(256, 33, 'মেহেন্দিগঞ্জ', 'Mehendiganj', NULL, NULL, NULL),
	(257, 33, 'মুলাদী', 'Muladi', NULL, NULL, NULL),
	(258, 33, 'হিজলা', 'Hizla', NULL, NULL, NULL),
	(259, 34, 'ভোলা সদর', 'Bhola Sadar', NULL, NULL, NULL),
	(260, 34, 'বোরহান উদ্দিন', 'Borhan Sddin', NULL, NULL, NULL),
	(261, 34, 'চরফ্যাশন', 'Charfesson', NULL, NULL, NULL),
	(262, 34, 'দৌলতখান', 'Doulatkhan', NULL, NULL, NULL),
	(263, 34, 'মনপুরা', 'Monpura', NULL, NULL, NULL),
	(264, 34, 'তজুমদ্দিন', 'Tazumuddin', NULL, NULL, NULL),
	(265, 34, 'লালমোহন', 'Lalmohan', NULL, NULL, NULL),
	(266, 35, 'আমতলী', 'Amtali', NULL, NULL, NULL),
	(267, 35, 'বরগুনা সদর', 'Barguna Sadar', NULL, NULL, NULL),
	(268, 35, 'বেতাগী', 'Betagi', NULL, NULL, NULL),
	(269, 35, 'বামনা', 'Bamna', NULL, NULL, NULL),
	(270, 35, 'পাথরঘাটা', 'Pathorghata', NULL, NULL, NULL),
	(271, 35, 'তালতলি', 'Taltali', NULL, NULL, NULL),
	(272, 36, 'বালাগঞ্জ', 'Balaganj', NULL, NULL, NULL),
	(273, 36, 'বিয়ানীবাজার', 'Beanibazar', NULL, NULL, NULL),
	(274, 36, 'বিশ্বনাথ', 'Bishwanath', NULL, NULL, NULL),
	(275, 36, 'কোম্পানীগঞ্জ', 'Companiganj', NULL, NULL, NULL),
	(276, 36, 'ফেঞ্চুগঞ্জ', 'Fenchuganj', NULL, NULL, NULL),
	(277, 36, 'গোলাপগঞ্জ', 'Golapganj', NULL, NULL, NULL),
	(278, 36, 'গোয়াইনঘাট', 'Gowainghat', NULL, NULL, NULL),
	(279, 36, 'জৈন্তাপুর', 'Jaintiapur', NULL, NULL, NULL),
	(280, 36, 'কানাইঘাট', 'Kanaighat', NULL, NULL, NULL),
	(281, 36, 'সিলেট সদর', 'Sylhet Sadar', NULL, NULL, NULL),
	(282, 36, 'জকিগঞ্জ', 'Zakiganj', NULL, NULL, NULL),
	(283, 36, 'দক্ষিণ সুরমা', 'Dakshinsurma', NULL, NULL, NULL),
	(284, 36, 'ওসমানী নগর', 'Osmaninagar', NULL, NULL, NULL),
	(285, 37, 'বড়লেখা', 'Barlekha', NULL, NULL, NULL),
	(286, 37, 'কমলগঞ্জ', 'Kamolganj', NULL, NULL, NULL),
	(287, 37, 'কুলাউড়া', 'Kulaura', NULL, NULL, NULL),
	(288, 37, 'মৌলভীবাজার সদর', 'Moulvibazar Sadar', NULL, NULL, NULL),
	(289, 37, 'রাজনগর', 'Rajnagar', NULL, NULL, NULL),
	(290, 37, 'শ্রীমঙ্গল', 'Sreemangal', NULL, NULL, NULL),
	(291, 37, 'জুড়ী', 'Juri', NULL, NULL, NULL),
	(292, 38, 'নবীগঞ্জ', 'Nabiganj', NULL, NULL, NULL),
	(293, 38, 'বাহুবল', 'Bahubal', NULL, NULL, NULL),
	(294, 38, 'আজমিরীগঞ্জ', 'Ajmiriganj', NULL, NULL, NULL),
	(295, 38, 'বানিয়াচং', 'Baniachong', NULL, NULL, NULL),
	(296, 38, 'লাখাই', 'Lakhai', NULL, NULL, NULL),
	(297, 38, 'চুনারুঘাট', 'Chunarughat', NULL, NULL, NULL),
	(298, 38, 'হবিগঞ্জ সদর', 'Habiganj Sadar', NULL, NULL, NULL),
	(299, 38, 'মাধবপুর', 'Madhabpur', NULL, NULL, NULL),
	(300, 39, 'সুনামগঞ্জ সদর', 'Sunamganj Sadar', NULL, NULL, NULL),
	(301, 39, 'দক্ষিণ সুনামগঞ্জ', 'South Sunamganj', NULL, NULL, NULL),
	(302, 39, 'বিশ্বম্ভরপুর', 'Bishwambarpur', NULL, NULL, NULL),
	(303, 39, 'ছাতক', 'Chhatak', NULL, NULL, NULL),
	(304, 39, 'জগন্নাথপুর', 'Jagannathpur', NULL, NULL, NULL),
	(305, 39, 'দোয়ারাবাজার', 'Dowarabazar', NULL, NULL, NULL),
	(306, 39, 'তাহিরপুর', 'Tahirpur', NULL, NULL, NULL),
	(307, 39, 'ধর্মপাশা', 'Dharmapasha', NULL, NULL, NULL),
	(308, 39, 'জামালগঞ্জ', 'Jamalganj', NULL, NULL, NULL),
	(309, 39, 'শাল্লা', 'Shalla', NULL, NULL, NULL),
	(310, 39, 'দিরাই', 'Derai', NULL, NULL, NULL),
	(311, 40, 'বেলাবো', 'Belabo', NULL, NULL, NULL),
	(312, 40, 'মনোহরদী', 'Monohardi', NULL, NULL, NULL),
	(313, 40, 'নরসিংদী সদর', 'Narsingdi Sadar', NULL, NULL, NULL),
	(314, 40, 'পলাশ', 'Palash', NULL, NULL, NULL),
	(315, 40, 'রায়পুরা', 'Raipura', NULL, NULL, NULL),
	(316, 40, 'শিবপুর', 'Shibpur', NULL, NULL, NULL),
	(317, 41, 'কালীগঞ্জ', 'Kaliganj', NULL, NULL, NULL),
	(318, 41, 'কালিয়াকৈর', 'Kaliakair', NULL, NULL, NULL),
	(319, 41, 'কাপাসিয়া', 'Kapasia', NULL, NULL, NULL),
	(320, 41, 'গাজীপুর সদর', 'Gazipur Sadar', NULL, NULL, NULL),
	(321, 41, 'শ্রীপুর', 'Sreepur', NULL, NULL, NULL),
	(322, 42, 'শরিয়তপুর সদর', 'Shariatpur Sadar', NULL, NULL, NULL),
	(323, 42, 'নড়িয়া', 'Naria', NULL, NULL, NULL),
	(324, 42, 'জাজিরা', 'Zajira', NULL, NULL, NULL),
	(325, 42, 'গোসাইরহাট', 'Gosairhat', NULL, NULL, NULL),
	(326, 42, 'ভেদরগঞ্জ', 'Bhedarganj', NULL, NULL, NULL),
	(327, 42, 'ডামুড্যা', 'Damudya', NULL, NULL, NULL),
	(328, 43, 'আড়াইহাজার', 'Araihazar', NULL, NULL, NULL),
	(329, 43, 'বন্দর', 'Bandar', NULL, NULL, NULL),
	(330, 43, 'নারায়নগঞ্জ সদর', 'Narayanganj Sadar', NULL, NULL, NULL),
	(331, 43, 'রূপগঞ্জ', 'Rupganj', NULL, NULL, NULL),
	(332, 43, 'সোনারগাঁ', 'Sonargaon', NULL, NULL, NULL),
	(333, 44, 'বাসাইল', 'Basail', NULL, NULL, NULL),
	(334, 44, 'ভুয়াপুর', 'Bhuapur', NULL, NULL, NULL),
	(335, 44, 'দেলদুয়ার', 'Delduar', NULL, NULL, NULL),
	(336, 44, 'ঘাটাইল', 'Ghatail', NULL, NULL, NULL),
	(337, 44, 'গোপালপুর', 'Gopalpur', NULL, NULL, NULL),
	(338, 44, 'মধুপুর', 'Madhupur', NULL, NULL, NULL),
	(339, 44, 'মির্জাপুর', 'Mirzapur', NULL, NULL, NULL),
	(340, 44, 'নাগরপুর', 'Nagarpur', NULL, NULL, NULL),
	(341, 44, 'সখিপুর', 'Sakhipur', NULL, NULL, NULL),
	(342, 44, 'টাঙ্গাইল সদর', 'Tangail Sadar', NULL, NULL, NULL),
	(343, 44, 'কালিহাতী', 'Kalihati', NULL, NULL, NULL),
	(344, 44, 'ধনবাড়ী', 'Dhanbari', NULL, NULL, NULL),
	(345, 45, 'ইটনা', 'Itna', NULL, NULL, NULL),
	(346, 45, 'কটিয়াদী', 'Katiadi', NULL, NULL, NULL),
	(347, 45, 'ভৈরব', 'Bhairab', NULL, NULL, NULL),
	(348, 45, 'তাড়াইল', 'Tarail', NULL, NULL, NULL),
	(349, 45, 'হোসেনপুর', 'Hossainpur', NULL, NULL, NULL),
	(350, 45, 'পাকুন্দিয়া', 'Pakundia', NULL, NULL, NULL),
	(351, 45, 'কুলিয়ারচর', 'Kuliarchar', NULL, NULL, NULL),
	(352, 45, 'কিশোরগঞ্জ সদর', 'Kishoreganj Sadar', NULL, NULL, NULL),
	(353, 45, 'করিমগঞ্জ', 'Karimgonj', NULL, NULL, NULL),
	(354, 45, 'বাজিতপুর', 'Bajitpur', NULL, NULL, NULL),
	(355, 45, 'অষ্টগ্রাম', 'Austagram', NULL, NULL, NULL),
	(356, 45, 'মিঠামইন', 'Mithamoin', NULL, NULL, NULL),
	(357, 45, 'নিকলী', 'Nikli', NULL, NULL, NULL),
	(358, 46, 'হরিরামপুর', 'Harirampur', NULL, NULL, NULL),
	(359, 46, 'সাটুরিয়া', 'Saturia', NULL, NULL, NULL),
	(360, 46, 'মানিকগঞ্জ সদর', 'Manikganj Sadar', NULL, NULL, NULL),
	(361, 46, 'ঘিওর', 'Gior', NULL, NULL, NULL),
	(362, 46, 'শিবালয়', 'Shibaloy', NULL, NULL, NULL),
	(363, 46, 'দৌলতপুর', 'Doulatpur', NULL, NULL, NULL),
	(364, 46, 'সিংগাইর', 'Singiar', NULL, NULL, NULL),
	(365, 47, 'সাভার', 'Savar', NULL, NULL, NULL),
	(366, 47, 'ধামরাই', 'Dhamrai', NULL, NULL, NULL),
	(367, 47, 'কেরাণীগঞ্জ', 'Keraniganj', NULL, NULL, NULL),
	(368, 47, 'নবাবগঞ্জ', 'Nawabganj', NULL, NULL, NULL),
	(369, 47, 'দোহার', 'Dohar', NULL, NULL, NULL),
	(370, 48, 'মুন্সিগঞ্জ সদর', 'Munshiganj Sadar', NULL, NULL, NULL),
	(371, 48, 'শ্রীনগর', 'Sreenagar', NULL, NULL, NULL),
	(372, 48, 'সিরাজদিখান', 'Sirajdikhan', NULL, NULL, NULL),
	(373, 48, 'লৌহজং', 'Louhajanj', NULL, NULL, NULL),
	(374, 48, 'গজারিয়া', 'Gajaria', NULL, NULL, NULL),
	(375, 48, 'টংগীবাড়ি', 'Tongibari', NULL, NULL, NULL),
	(376, 49, 'রাজবাড়ী সদর', 'Rajbari Sadar', NULL, NULL, NULL),
	(377, 49, 'গোয়ালন্দ', 'Goalanda', NULL, NULL, NULL),
	(378, 49, 'পাংশা', 'Pangsa', NULL, NULL, NULL),
	(379, 49, 'বালিয়াকান্দি', 'Baliakandi', NULL, NULL, NULL),
	(380, 49, 'কালুখালী', 'Kalukhali', NULL, NULL, NULL),
	(381, 50, 'মাদারীপুর সদর', 'Madaripur Sadar', NULL, NULL, NULL),
	(382, 50, 'শিবচর', 'Shibchar', NULL, NULL, NULL),
	(383, 50, 'কালকিনি', 'Kalkini', NULL, NULL, NULL),
	(384, 50, 'রাজৈর', 'Rajoir', NULL, NULL, NULL),
	(385, 51, 'গোপালগঞ্জ সদর', 'Gopalganj Sadar', NULL, NULL, NULL),
	(386, 51, 'কাশিয়ানী', 'Kashiani', NULL, NULL, NULL),
	(387, 51, 'টুংগীপাড়া', 'Tungipara', NULL, NULL, NULL),
	(388, 51, 'কোটালীপাড়া', 'Kotalipara', NULL, NULL, NULL),
	(389, 51, 'মুকসুদপুর', 'Muksudpur', NULL, NULL, NULL),
	(390, 52, 'ফরিদপুর সদর', 'Faridpur Sadar', NULL, NULL, NULL),
	(391, 52, 'আলফাডাঙ্গা', 'Alfadanga', NULL, NULL, NULL),
	(392, 52, 'বোয়ালমারী', 'Boalmari', NULL, NULL, NULL),
	(393, 52, 'সদরপুর', 'Sadarpur', NULL, NULL, NULL),
	(394, 52, 'নগরকান্দা', 'Nagarkanda', NULL, NULL, NULL),
	(395, 52, 'ভাঙ্গা', 'Bhanga', NULL, NULL, NULL),
	(396, 52, 'চরভদ্রাসন', 'Charbhadrasan', NULL, NULL, NULL),
	(397, 52, 'মধুখালী', 'Madhukhali', NULL, NULL, NULL),
	(398, 52, 'সালথা', 'Saltha', NULL, NULL, NULL),
	(399, 53, 'পঞ্চগড় সদর', 'Panchagarh Sadar', NULL, NULL, NULL),
	(400, 53, 'দেবীগঞ্জ', 'Debiganj', NULL, NULL, NULL),
	(401, 53, 'বোদা', 'Boda', NULL, NULL, NULL),
	(402, 53, 'আটোয়ারী', 'Atwari', NULL, NULL, NULL),
	(403, 53, 'তেতুলিয়া', 'Tetulia', NULL, NULL, NULL),
	(404, 54, 'নবাবগঞ্জ', 'Nawabganj', NULL, NULL, NULL),
	(405, 54, 'বীরগঞ্জ', 'Birganj', NULL, NULL, NULL),
	(406, 54, 'ঘোড়াঘাট', 'Ghoraghat', NULL, NULL, NULL),
	(407, 54, 'বিরামপুর', 'Birampur', NULL, NULL, NULL),
	(408, 54, 'পার্বতীপুর', 'Parbatipur', NULL, NULL, NULL),
	(409, 54, 'বোচাগঞ্জ', 'Bochaganj', NULL, NULL, NULL),
	(410, 54, 'কাহারোল', 'Kaharol', NULL, NULL, NULL),
	(411, 54, 'ফুলবাড়ী', 'Fulbari', NULL, NULL, NULL),
	(412, 54, 'দিনাজপুর সদর', 'Dinajpur Sadar', NULL, NULL, NULL),
	(413, 54, 'হাকিমপুর', 'Hakimpur', NULL, NULL, NULL),
	(414, 54, 'খানসামা', 'Khansama', NULL, NULL, NULL),
	(415, 54, 'বিরল', 'Birol', NULL, NULL, NULL),
	(416, 54, 'চিরিরবন্দর', 'Chirirbandar', NULL, NULL, NULL),
	(417, 55, 'লালমনিরহাট সদর', 'Lalmonirhat Sadar', NULL, NULL, NULL),
	(418, 55, 'কালীগঞ্জ', 'Kaliganj', NULL, NULL, NULL),
	(419, 55, 'হাতীবান্ধা', 'Hatibandha', NULL, NULL, NULL),
	(420, 55, 'পাটগ্রাম', 'Patgram', NULL, NULL, NULL),
	(421, 55, 'আদিতমারী', 'Aditmari', NULL, NULL, NULL),
	(422, 56, 'সৈয়দপুর', 'Syedpur', NULL, NULL, NULL),
	(423, 56, 'ডোমার', 'Domar', NULL, NULL, NULL),
	(424, 56, 'ডিমলা', 'Dimla', NULL, NULL, NULL),
	(425, 56, 'জলঢাকা', 'Jaldhaka', NULL, NULL, NULL),
	(426, 56, 'কিশোরগঞ্জ', 'Kishorganj', NULL, NULL, NULL),
	(427, 56, 'নীলফামারী সদর', 'Nilphamari Sadar', NULL, NULL, NULL),
	(428, 57, 'সাদুল্লাপুর', 'Sadullapur', NULL, NULL, NULL),
	(429, 57, 'গাইবান্ধা সদর', 'Gaibandha Sadar', NULL, NULL, NULL),
	(430, 57, 'পলাশবাড়ী', 'Palashbari', NULL, NULL, NULL),
	(431, 57, 'সাঘাটা', 'Saghata', NULL, NULL, NULL),
	(432, 57, 'গোবিন্দগঞ্জ', 'Gobindaganj', NULL, NULL, NULL),
	(433, 57, 'সুন্দরগঞ্জ', 'Sundarganj', NULL, NULL, NULL),
	(434, 57, 'ফুলছড়ি', 'Phulchari', NULL, NULL, NULL),
	(435, 58, 'ঠাকুরগাঁও সদর', 'Thakurgaon Sadar', NULL, NULL, NULL),
	(436, 58, 'পীরগঞ্জ', 'Pirganj', NULL, NULL, NULL),
	(437, 58, 'রাণীশংকৈল', 'Ranisankail', NULL, NULL, NULL),
	(438, 58, 'হরিপুর', 'Haripur', NULL, NULL, NULL),
	(439, 58, 'বালিয়াডাঙ্গী', 'Baliadangi', NULL, NULL, NULL),
	(440, 59, 'রংপুর সদর', 'Rangpur Sadar', NULL, NULL, NULL),
	(441, 59, 'গংগাচড়া', 'Gangachara', NULL, NULL, NULL),
	(442, 59, 'তারাগঞ্জ', 'Taragonj', NULL, NULL, NULL),
	(443, 59, 'বদরগঞ্জ', 'Badargonj', NULL, NULL, NULL),
	(444, 59, 'মিঠাপুকুর', 'Mithapukur', NULL, NULL, NULL),
	(445, 59, 'পীরগঞ্জ', 'Pirgonj', NULL, NULL, NULL),
	(446, 59, 'কাউনিয়া', 'Kaunia', NULL, NULL, NULL),
	(447, 59, 'পীরগাছা', 'Pirgacha', NULL, NULL, NULL),
	(448, 60, 'কুড়িগ্রাম সদর', 'Kurigram Sadar', NULL, NULL, NULL),
	(449, 60, 'নাগেশ্বরী', 'Nageshwari', NULL, NULL, NULL),
	(450, 60, 'ভুরুঙ্গামারী', 'Bhurungamari', NULL, NULL, NULL),
	(451, 60, 'ফুলবাড়ী', 'Phulbari', NULL, NULL, NULL),
	(452, 60, 'রাজারহাট', 'Rajarhat', NULL, NULL, NULL),
	(453, 60, 'উলিপুর', 'Ulipur', NULL, NULL, NULL),
	(454, 60, 'চিলমারী', 'Chilmari', NULL, NULL, NULL),
	(455, 60, 'রৌমারী', 'Rowmari', NULL, NULL, NULL),
	(456, 60, 'চর রাজিবপুর', 'Charrajibpur', NULL, NULL, NULL),
	(457, 61, 'শেরপুর সদর', 'Sherpur Sadar', NULL, NULL, NULL),
	(458, 61, 'নালিতাবাড়ী', 'Nalitabari', NULL, NULL, NULL),
	(459, 61, 'শ্রীবরদী', 'Sreebordi', NULL, NULL, NULL),
	(460, 61, 'নকলা', 'Nokla', NULL, NULL, NULL),
	(461, 61, 'ঝিনাইগাতী', 'Jhenaigati', NULL, NULL, NULL),
	(462, 62, 'ফুলবাড়ীয়া', 'Fulbaria', NULL, NULL, NULL),
	(463, 62, 'ত্রিশাল', 'Trishal', NULL, NULL, NULL),
	(464, 62, 'ভালুকা', 'Bhaluka', NULL, NULL, NULL),
	(465, 62, 'মুক্তাগাছা', 'Muktagacha', NULL, NULL, NULL),
	(466, 62, 'ময়মনসিংহ সদর', 'Mymensingh Sadar', NULL, NULL, NULL),
	(467, 62, 'ধোবাউড়া', 'Dhobaura', NULL, NULL, NULL),
	(468, 62, 'ফুলপুর', 'Phulpur', NULL, NULL, NULL),
	(469, 62, 'হালুয়াঘাট', 'Haluaghat', NULL, NULL, NULL),
	(470, 62, 'গৌরীপুর', 'Gouripur', NULL, NULL, NULL),
	(471, 62, 'গফরগাঁও', 'Gafargaon', NULL, NULL, NULL),
	(472, 62, 'ঈশ্বরগঞ্জ', 'Iswarganj', NULL, NULL, NULL),
	(473, 62, 'নান্দাইল', 'Nandail', NULL, NULL, NULL),
	(474, 62, 'তারাকান্দা', 'Tarakanda', NULL, NULL, NULL),
	(475, 63, 'জামালপুর সদর', 'Jamalpur Sadar', NULL, NULL, NULL),
	(476, 63, 'মেলান্দহ', 'Melandah', NULL, NULL, NULL),
	(477, 63, 'ইসলামপুর', 'Islampur', NULL, NULL, NULL),
	(478, 63, 'দেওয়ানগঞ্জ', 'Dewangonj', NULL, NULL, NULL),
	(479, 63, 'সরিষাবাড়ী', 'Sarishabari', NULL, NULL, NULL),
	(480, 63, 'মাদারগঞ্জ', 'Madarganj', NULL, NULL, NULL),
	(481, 63, 'বকশীগঞ্জ', 'Bokshiganj', NULL, NULL, NULL),
	(482, 64, 'বারহাট্টা', 'Barhatta', NULL, NULL, NULL),
	(483, 64, 'দুর্গাপুর', 'Durgapur', NULL, NULL, NULL),
	(484, 64, 'কেন্দুয়া', 'Kendua', NULL, NULL, NULL),
	(485, 64, 'আটপাড়া', 'Atpara', NULL, NULL, NULL),
	(486, 64, 'মদন', 'Madan', NULL, NULL, NULL),
	(487, 64, 'খালিয়াজুরী', 'Khaliajuri', NULL, NULL, NULL),
	(488, 64, 'কলমাকান্দা', 'Kalmakanda', NULL, NULL, NULL),
	(489, 64, 'মোহনগঞ্জ', 'Mohongonj', NULL, NULL, NULL),
	(490, 64, 'পূর্বধলা', 'Purbadhala', NULL, NULL, NULL),
	(491, 64, 'নেত্রকোণা সদর', 'Netrokona Sadar', NULL, NULL, NULL),
	(492, 47, 'আগারগাঁও', NULL, NULL, NULL, NULL),
	(493, 47, 'গেন্ডারিয়া', NULL, NULL, NULL, NULL),
	(494, 47, 'শাহবাগ', NULL, NULL, NULL, NULL),
	(495, 47, 'ধানমন্ডি', NULL, NULL, NULL, NULL),
	(496, 47, 'আজিমপুর', NULL, NULL, NULL, NULL),
	(497, 47, 'আদাবর', NULL, NULL, NULL, NULL),
	(498, 47, 'ইব্রাহিমপুর', NULL, NULL, NULL, NULL),
	(499, 47, 'ইস্কাটন', NULL, NULL, NULL, NULL),
	(500, 47, 'খিলক্ষেত', NULL, NULL, NULL, NULL),
	(501, 47, 'কাফরুল', NULL, NULL, NULL, NULL),
	(502, 47, 'মোহাম্মদপুর', NULL, NULL, NULL, NULL),
	(503, 47, 'সূত্রাপুর', NULL, NULL, NULL, NULL),
	(504, 47, 'যাত্রাবাড়ী', NULL, NULL, NULL, NULL),
	(505, 47, 'বিমানবন্দর', NULL, NULL, NULL, NULL),
	(506, 47, 'গুলশান', NULL, NULL, NULL, NULL),
	(507, 47, 'উত্তরা পশ্চিম', NULL, NULL, NULL, NULL),
	(508, 47, 'মুগদা', NULL, NULL, NULL, NULL),
	(509, 47, 'রূপনগর', NULL, NULL, NULL, NULL),
	(510, 47, 'ভাষানটেক', NULL, NULL, NULL, NULL),
	(511, 47, 'ভাটারা', NULL, NULL, NULL, NULL),
	(512, 47, 'বনানী', NULL, NULL, NULL, NULL),
	(513, 47, 'ওয়ারী', NULL, NULL, NULL, NULL),
	(514, 47, 'শাহজাহানপুর', NULL, NULL, NULL, NULL),
	(515, 47, 'শেরেবাংলা নগর', NULL, NULL, NULL, NULL),
	(516, 47, 'মিরপুর মডেল থানা', NULL, NULL, NULL, NULL),
	(517, 47, 'দারুস সালাম', NULL, NULL, NULL, NULL),
	(518, 47, 'দক্ষিণখান', NULL, NULL, NULL, NULL),
	(519, 47, 'উত্তরখান', NULL, NULL, NULL, NULL),
	(520, 47, 'তুরাগ', NULL, NULL, NULL, NULL),
	(521, 47, 'উত্তরা মডেল থানা', NULL, NULL, NULL, NULL),
	(522, 47, 'ক্যান্টনমেন্ট', NULL, NULL, NULL, NULL),
	(523, 47, 'বাড্ডা', NULL, NULL, NULL, NULL),
	(524, 47, 'পল্লবী', NULL, NULL, NULL, NULL),
	(525, 47, 'শাহআলী', NULL, NULL, NULL, NULL),
	(526, 47, 'তেজঁগাও শিল্পাঞ্চল', NULL, NULL, NULL, NULL),
	(527, 47, 'তেজঁগাও', NULL, NULL, NULL, NULL),
	(528, 47, 'রামপুরা', NULL, NULL, NULL, NULL),
	(529, 47, 'সবুজবাগ', NULL, NULL, NULL, NULL),
	(530, 47, 'কদমতলী', NULL, NULL, NULL, NULL),
	(531, 47, 'চকবাজার', NULL, NULL, NULL, NULL),
	(532, 47, 'কামরাঙ্গীরচর', NULL, NULL, NULL, NULL),
	(533, 47, 'কোতয়ালী', NULL, NULL, NULL, NULL),
	(534, 47, 'লালবাগ', NULL, NULL, NULL, NULL),
	(535, 47, 'কলাবাগান', NULL, NULL, NULL, NULL),
	(536, 47, 'মতিঝিল', NULL, NULL, NULL, NULL),
	(537, 47, 'খিলগাঁও', NULL, NULL, NULL, NULL),
	(538, 47, 'হাজারীবাগ', NULL, NULL, NULL, NULL),
	(539, 47, 'রমনা মডেল থানা', NULL, NULL, NULL, NULL),
	(540, 47, 'ডেমরা', NULL, NULL, NULL, NULL),
	(541, 47, 'পল্টন মডেল থানা', NULL, NULL, NULL, NULL),
	(542, 47, 'বংশাল', NULL, NULL, NULL, NULL),
	(543, 47, 'নিউমার্কেট', NULL, NULL, NULL, NULL),
	(544, 47, 'শ্যামপুর', NULL, NULL, NULL, NULL),
	(545, 27, 'খুলনা সিটি', NULL, NULL, NULL, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
